name: Development test

on:
  push:
    branches:
      - develop

jobs:
  build:
    name: Development test
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install Node.js
      uses: actions/setup-node@v1
      with:
        node-version: 13.x

    - name: Install NPM packages
      run: npm ci

    - name: Run tests
      run: npm run test
